name: Build
on: [push]

jobs:
  build_msvc:
    name: Visual Studio Building
    runs-on: windows-2019
    steps:
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Install Windows 8.1 SDK
      shell: powershell
      run: |
        Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
        Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      run: msbuild CnCRemastered.sln
